apiVersion: v1
data:
  secrets.conf: |
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUJDREVGR0hJSjAxMjM0NTY3ODkKYX
    dzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gT3czSFVhUDhCYnFrVjRkVXJacjBIN3lUNW5HUDVP
    UEZjWkor
kind: Secret
metadata:
  name: example-secret-1-268t6t22gf
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: my-app
        name: app
        volumeMounts:
        - mountPath: /secrets
          name: password
      volumes:
      - name: password
        secret:
          secretName: example-secret-1-268t6t22gf
