apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pod.yaml
- secret.yaml

# vars:
# - name: SOME_SECRET_NAME
#   objref:
#     kind: Secret
#     name: my-secret
#     apiVersion: v1

replacements:
- source:
    kind: Secret
    name: my-secret
    version: v1
    fieldPath: data.username
  targets:
  - select: 
      kind: Pod
      name: my-pod
    fieldPaths:
    - spec.containers.[name=hello].env.[name=SECRET_TOKEN].value