apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: myimage
    name: hello
    env:
    - name: SECRET_TOKEN
      #value: $(SOME_SECRET_NAME)
      value: SOME_PLACEHOLDER_VALUE
