apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deploy-patch.yaml
- path: deploy-more-patch.yaml
  target:
    kind: Deployment

configMapGenerator:
- name: config
  behavior: merge
  literals:
    - custom="My Custom Config"